### ISSUE TITLE
Issue with pytest

### ISSUE THREAD

**Issue by jkrol8** [Extensible-Clinical-Imaging-QC-Tool/PKModelProject#44]
It seems that almost all workflows  currently fail as they can't run the pytest tests ('no module named pytest')

**Comment by EmmanuelleB985** [comment]
I am sorry I added this in the installments this morning because I used pytest for my parametrised tests and it failed with unit test. So it is not possible to have the two? Then we can go back to the previous version
Ok so we can do parametrised tests with unit tests as well, I will fix that.

________________________________

**Comment by EmmanuelleB985** [comment]
It should be fixed now
